version: 2.1

jobs:
  eslint:
    docker:
      - image: node:slim
    steps:
      - checkout
      - run:
          name: Setup NPM
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
          
  Unit-Tests:
    docker:
      - image: nimlang/nim:1.6.4-alpine-regular

    steps:
      - checkout
      - run:
          name: Install poppler
          command: apk add poppler-utils file

      - run:
          name: Update nimble
          command: nimble update -y
          
      - run:
          name: Run test suite
          command: nimble test

workflows:
  Tests:
    jobs:
      - eslint
      - Unit-Tests:
          requires: 
            - eslint
