version: 2.1

jobs:          
  Unit-Tests:
    docker:
      - image: nimlang/nim:1.6.12-alpine-regular

    steps:
      - checkout
      - run:
          name: Install poppler
          command: apk add poppler-utils file

      - run:
          name: Update nimble
          command: nimble update -y
      - run:
          name: Check build
          command: nimble build -y
      - run:
          name: Run test suite
          command: nimble test -y

workflows:
  Tests:
    jobs:
      - Unit-Tests
