version: 2.1

jobs:
  Unit-Tests:
    docker:
      - image: nimlang/nim:1.6.4-alpine-regular

    steps:
      - checkout
      - run:
          name: Install poppler
          command: apk add poppler
      - run:
          name: Run test suite
          command: nimble test
workflows:
  Tests:
    jobs:
      - Unit-Tests
